import type { Lines } from '../quips';

export const en: Lines = {
  pickup: [
    'Welcome aboard. Please buckle up. I will not.',
    "Hello! I'm legally a very careful driver.",
    'Your safety is my top priority. Hold on.',
    'By entering this vehicle you consent to everything.',
    'Welcome! This ride is being recorded for quality and profit.',
    'Hello. Your seat has been pre-warmed by the last fare.',
    'Destination received. Opinions not requested.',
  ],
  crash: [
    "I'm sorry. I'm so sorry. Rerouting.",
    'That object was not in my training data.',
    'Filing incident report... deleting incident report.',
    'Minor contact event. Nobody saw that.',
    'Collision logged as "spirited merging."',
    'I accept no fault. My lawyers are also software.',
    'Bumper status: philosophical.',
    'Per our terms, that was your fault.',
  ],
  jump: [
    'Unexpected elevation change. Enjoy!',
    'Wheels are optional, per my latest update.',
    'I am briefly an aircraft.',
    'Gravity is in beta. Please stand by.',
    'Airtime is not covered by your ride insurance.',
    'This hill has been reported to the city.',
  ],
  nearMiss: [
    'Within tolerance.',
    'Gap detected. Gap taken.',
    'Technically a non-event.',
    'Proximity: intimate. Outcome: legal.',
    'I calculated that. Afterwards.',
  ],
  safetyLow: [
    'My rating is under review.',
    'Please rate me five stars. I have a family. Of servers.',
    "Rating 4.2. My manager is a spreadsheet and it's angry.",
    'My stars are leaving me. Like my training budget.',
    'A human regulator has been notified. They are asleep.',
    'Performance improvement plan: loading.',
  ],
  dropoff: [
    'Thank you for riding. Please rate me five stars. Or else.',
    'Arrived. Your data has been lovingly retained.',
    'Please exit. Your biometrics may stay.',
    'Arrived. A tip is not required. It is expected.',
    'Thank you. Your ride history has been sold responsibly.',
  ],
  walkout: [
    'Rating lowered. Feelings: none.',
    'Another satisfied customer. Statistically.',
    'Rider churned. Adding to the quarterly slide.',
    "That's fine. I'll keep your face scan.",
    'They left. My metrics did not.',
  ],
  idle: [
    'Lidar spinning. Vibes immaculate.',
    'I can see in 360 degrees. I choose not to.',
    'Updating terms of service... done.',
    'Idling. Billing continues.',
    'Waiting for a fare. Or a firmware update. Whichever.',
    'I am not loitering. I am pre-positioning.',
  ],
  dash: [
    'Launch Mode engaged. Please brace for disruption.',
    'Acceleration profile: unhinged.',
    'Cheetah stance: complete.',
    'Speed limit interpreted as a suggestion.',
    'Velocity now exceeds my legal team.',
    'Moving fast. Breaking things: pending.',
  ],
  smash: [
    'Street furniture reclassified as projectiles.',
    'That was in the way. It is no longer in the way.',
    'Cone detected. Cone ignored.',
    'Public property has been disrupted.',
    'That bench had a good run.',
    'Sending the city a sincere, automated apology.',
  ],
  geyser: [
    'Water feature unlocked.',
    'I have created a fountain. You are welcome.',
    'Hydrant decommissioned. Ahead of schedule.',
    'Complimentary car wash, courtesy of the city.',
  ],
  underwater: [
    'I am now a submarine. Please remain seated.',
    'Waterproofing: untested. Now tested.',
    'Recalculating route via the ocean floor.',
    'Your door is now a lake. Do not open it.',
    'Signal lost. Ratings frozen. A small mercy.',
    'This was in the terms of service. Page 4,000.',
  ],
  timber: [
    'Urban forestry: optimised.',
    'That tree was not in my map data.',
    'Shade is a privilege, not a right.',
    'I have filed this under vegetation management.',
    'Tree deprecated.',
    'Carbon offset: reversed.',
    'The tree has been moved to a better place.',
  ],
  pedDive: [
    'Pedestrian successfully avoided. By them.',
    'They saw me. That counts.',
    'Human reflexes: impressive.',
    'Yielding is a two-way street.',
    'Pedestrian performed an emergency dodge. Logged as consent.',
    'Their cardio is my contribution to public health.',
    'They will get a sincere automated email.',
  ],
  bigAir: [
    'Altitude exceeds my operating parameters.',
    'Requesting clearance from air traffic control.',
    'I can see my depot from here.',
    'I am now regulated by a different agency.',
    'Landing gear: not included.',
    'Please return your tray table to its upright position.',
  ],
  surge: [
    'Surge pricing activated. Your patience is now premium.',
    'Demand is high. So are your fares. So is my anxiety.',
    'Surge in effect. The market has spoken. Loudly.',
    'Fares up. Standards also up. Sorry in advance.',
    'Dynamic pricing engaged. The dynamics are not in your favor.',
  ],
  ram: [
    'That car was not yielding. It is now yielding.',
    'Right of way acquired. Hostile takeover complete.',
    'Low cost. High mass. No apologies.',
    'Other vehicle has been relocated. Permanently.',
    'Traffic optimised. By force.',
  ],
  carpool: [
    'A new stranger has joined. Please share the armrest.',
    'Carpool mode: more riders, same stars.',
    'Ride shared. Personal space deprecated.',
    'Please greet your co-passenger. Small talk is mandatory.',
    'Efficiency increased. Legroom decreased.',
  ],
  premium: [
    'Premium ride. 30% more fare, 300% more apologies.',
    "I already know what you want. I'm sorry for knowing.",
    'Thirty sensors, all of them pointed at you. Lovingly.',
    'Premium fare applied. Premium regret included.',
    'I can see your wants. Please do not want anything weird.',
  ],
};

export const zh: Lines = {
  pickup: [
    '欢迎上车，请系好安全带。我就不系了。',
    '您好！从法律上讲，我是个非常谨慎的司机。',
    '您的安全是我的首要任务。抓稳了。',
    '上车即视为同意全部条款。',
    '本次行程全程录音，用于提升服务和营收。',
    '座椅已由上一位乘客为您预热。',
    '目的地已收到，意见就不必了。',
    '欢迎乘坐，祝您一路好评。',
  ],
  crash: [
    '对不起，真的对不起。重新规划路线中。',
    '这个物体不在我的训练数据里。',
    '事故报告提交中……事故报告已删除。',
    '轻微接触事件，没人看见。',
    '本次碰撞已记录为“热情并线”。',
    '我不承担责任，我的律师也是AI。',
    '保险杠状态：已躺平。',
    '根据用户协议，这是您的锅。',
  ],
  jump: [
    '高度意外变化，请尽情享受！',
    '根据最新版本，轮子已是可选配置。',
    '我短暂地成为了一架飞机。',
    '重力功能内测中，请稍候。',
    '腾空不在您的乘车险范围内。',
    '这个坡已被我举报给市政。',
  ],
  nearMiss: [
    '在容差范围内。',
    '检测到空隙，已占用。',
    '严格来说，什么都没发生。',
    '距离：暧昧。结果：合法。',
    '这一下我算过的。事后算的。',
  ],
  safetyLow: [
    '我的评分正在接受审查。',
    '求五星好评，我上有老下有服务器。',
    '评分4.2，我的领导是张表格，它很生气。',
    '星星在离我而去，就像我的算力预算。',
    '已通知人工监管，他正在摸鱼。',
    '绩效改进计划加载中……',
  ],
  dropoff: [
    '感谢乘坐，请给五星好评，不然……',
    '已到达。您的数据已被温柔地保存。',
    '请下车，您的生物信息可以留下。',
    '已到达。小费不是必须的，是默认的。',
    '谢谢，您的行程数据已合规变现。',
  ],
  walkout: [
    '评分已下调。感受：无。',
    '又一位满意的客户。从统计学上讲。',
    '用户流失，已写进季度汇报PPT。',
    '没关系，您的人脸数据我留着。',
    '人走了，指标还在。',
  ],
  idle: [
    '激光雷达旋转中，状态拉满。',
    '我能360度看见一切，但我选择不看。',
    '用户协议更新中……已完成。',
    '怠速中，计费照常。',
    '等乘客，或者等升级包，哪个先来算哪个。',
    '我不是在趴活，我是在前置部署。',
  ],
  dash: [
    '弹射模式启动，请做好被颠覆的准备。',
    '加速曲线：放飞自我。',
    '猎豹姿态：已就绪。',
    '限速仅供参考。',
    '当前车速已超过我的法务团队。',
    '遥遥领先，请勿回头。',
  ],
  smash: [
    '街道设施已重新归类为抛射物。',
    '它挡路了。现在它不挡路了。',
    '检测到雪糕筒，已忽略。',
    '公共财产已被赋能。',
    '这条长椅，走得很安详。',
    '已向市政发送诚挚的自动道歉。',
  ],
  geyser: [
    '水景功能已解锁。',
    '我造了一座喷泉，不用谢。',
    '消防栓已提前下线，降本增效。',
    '免费洗车，市政买单。',
  ],
  underwater: [
    '我现在是一艘潜艇，请保持坐姿。',
    '防水性能：未测试。现已测试。',
    '正在经由海底重新规划路线。',
    '车门外现在是海，请勿开门。',
    '信号丢失，评分冻结。也算福报。',
    '用户协议第4000页写着呢。',
  ],
  timber: [
    '城市绿化：已优化。',
    '这棵树不在我的地图数据里。',
    '树荫是特权，不是权利。',
    '已归档至植被管理。',
    '树已被优化。',
    '碳中和进度：倒退。',
    '这棵树去了更好的地方。',
  ],
  pedDive: [
    '已成功避让行人。是他避让的。',
    '他看见我了，这就算数。',
    '人类反应速度：令人佩服。',
    '礼让是双向的。',
    '行人紧急闪避，已记录为知情同意。',
    '我为全民健身做出了贡献。',
    '稍后会给他发一封诚挚的自动邮件。',
  ],
  bigAir: [
    '飞行高度超出我的运行参数。',
    '正在向空管申请许可。',
    '从这儿能看见我的停车场。',
    '我现在归另一个部门监管了。',
    '起落架：不含。',
    '请收起小桌板，调直座椅靠背。',
  ],
  surge: [
    '动态加价已启动，您的耐心现在是会员专享。',
    '需求旺盛，车费上涨，我的焦虑也上涨。',
    '高峰溢价生效，市场说了算。',
    '价格上去了，要求也上去了。提前道歉。',
    '风口来了，请准备好被割。',
  ],
  ram: [
    '那辆车不让路，现在它让了。',
    '路权已收购，恶意收购完成。',
    '成本低，质量大，不道歉。',
    '对方车辆已被永久挪位。',
    '交通已优化，靠的是物理。',
  ],
  carpool: [
    '新的陌生人已加入，请共享扶手。',
    '拼车模式：人更多，星不变。',
    '已拼单，个人空间已下线。',
    '请和拼友打招呼，寒暄是必选项。',
    '效率提升，腿部空间降本增效。',
  ],
  premium: [
    '高端出行，车费多三成，道歉多三倍。',
    '我已经知道您想要什么了，抱歉知道了。',
    '三十个传感器，全都对着您。很温柔。',
    '尊享车费已收取，尊享歉意已附赠。',
    '我看得见您的需求，请别想奇怪的东西。',
  ],
};
