import type { Asks, Lines } from '../quips';

export const en: Lines = {
  pickup: [
    'Hiii, okay, can you find my good angle?',
    'Oh my god, a robot. So on brand.',
    'Hey! I need to be at my thing, like, now.',
    "Hiii! Wait, let me get the entrance. Okay. Go.",
    'Is the lighting in here always this bad?',
    "Hey bestie! We're going live in, like, two.",
    "Oh, a self-driving car? That's a whole campaign.",
  ],
  jumpFirst: [
    "Wait, do that again, I wasn't filming.",
    'Nooo, my phone was locked. Again!',
    'Hold on, I was on the wrong lens!',
    "Ugh, I was vertical. We need horizontal. Again!",
    "Was that a jump? I was replying to a DM.",
  ],
  jump: [
    "Okay THAT's the content!",
    "Posting that. Tagging you. What's your handle?",
    'Engagement is going to be insane.',
    'That was SO iconic. Slow-mo was on.',
    'Okay, that one is the thumbnail.',
    "That's giving main character.",
    'The algorithm is going to eat that up.',
    'Wait, that was perfect. Nobody breathe.',
  ],
  nearMiss: [
    'That was so close, I love that for us.',
    'Okay, chaos. Very authentic.',
    'Ooh, that was raw. Very unfiltered.',
    'I literally screamed. Keeping the audio.',
    "That's a whole storytime, honestly.",
    'Okay, adrenaline is so in this season.',
  ],
  crash: [
    'My lash extensions!',
    "Okay, we're cutting that part.",
    'Not the vibe. Not the vibe.',
    'My ring light!',
    'Okay, crisis comms. Nobody post anything.',
    'That is NOT on the mood board.',
  ],
  drift: [
    'The drift? Iconic.',
    'This is giving Tokyo.',
    'Oh my god, the slide. Obsessed.',
    'Sideways is my best angle, actually.',
    'This is so cinematic. Where is the drone?',
    'Okay, drift era. We love a drift era.',
  ],
  slow: [
    'This is so not giving speed.',
    'Can we be more... viral?',
    'This pacing is losing the audience.',
    'Speed it up, the story expires in 24 hours.',
    "This is giving buffering.",
    'My followers are literally scrolling past us.',
  ],
  timeLow: [
    "I'm going to be SO late to my own launch.",
    'Hurry, my matcha is dying.',
    "The influencers are arriving and I'm not there!",
    'The embargo lifts in five minutes, babe!',
    "If I'm late the brand is late. Go!",
    'My golden hour is ending!',
  ],
  dropoff: [
    "Thank youuu! I'll tag you!",
    'Five stars. The content was elite.',
    "Love that for me. Let's collab.",
    "Okay, you're officially a brand ambassador.",
    "Bye! Check my stories, you're in them!",
    "That ride was a whole moment. Obsessed.",
  ],
  walkout: [
    'Ugh. Calling a different robot.',
    "This is not aligned with my brand. Bye.",
    "Okay, I'm unfollowing this car.",
  ],
  idle: [
    "Our brand voice is basically 'unbothered.'",
    'I rebranded my dog this morning.',
    "We're a lifestyle brand. For B2B SaaS.",
    "My matcha has more followers than our CEO.",
    'I told legal "ok" and then I posted it anyway.',
    "Our north star metric is vibes.",
    "I'm launching a candle that smells like Q4.",
  ],
  smash: [
    'Wait, smash it again, I want the impact shot.',
    "Destruction is SO in right now.",
    'That was giving rebrand. Out with the old.',
    'Okay, chaotic. My audience will love it.',
  ],
  'good.air': [
    'The air time is literally giving.',
    'Okay, we have SO much B-roll.',
    'Engagement is up. Keep flying, babe.',
    "This is going to be the most iconic reel.",
  ],
  'bad.air': [
    'Babe, ground footage is not content.',
    "This is giving stock footage. Jump something!",
    'No air, no reel. No reel, no reach.',
    'My audience wants airtime. Literally.',
  ],
  'good.drift': [
    'This drift is serving. Keep serving.',
    'The slow-mo on this is unreal.',
    "Okay, the sideways content is elite.",
    'We are trending. I can feel it.',
  ],
  'bad.drift': [
    'Babe, straight lines are so last season.',
    "Where's the drift? Slow-mo is just sitting here.",
    'This is not giving Tokyo. This is giving commute.',
    'I promised the brand a drift. Drift!',
  ],
  carpool: [
    "Oh, a guest! Sign this release form. Kidding. Not kidding.",
    "Hi! Can you be in the background? Just vibe.",
    "Carpool content? Okay, relatable. I'm into it.",
    'Hey, new person. What is your follower count?',
  ],
  premium: [
    "1.3x? That's the influencer rate. Fine.",
    'Premium? Okay, it matches my aesthetic.',
    'The sensors are so editorial. Very futurecore.',
    "It said sorry so nicely. That's great brand voice.",
  ],
  ram: [
    'Okay, we just bulldozed a car? Iconic.',
    "That's what I call a hard launch.",
    "Move, babe, you're blocking my shot!",
  ],
};

export const zh: Lines = {
  pickup: [
    '嗨~师傅，能帮我找找我的上镜角度吗？',
    '天呐，机器人开车，太有品牌调性了。',
    '嘿！我那个活动要迟到了，快！',
    '等下，我先拍个上车镜头。好，走！',
    '这车里的光线一直这么拉胯吗？',
    '姐妹们，我们两分钟后开播哦！',
    '无人车？这就是一整个营销campaign啊。',
  ],
  jumpFirst: [
    '等等，再来一次，我刚没录！',
    '不要啊，我手机又锁屏了！',
    '等下，我刚刚镜头切错了！',
    '啊我拍的竖屏，要横屏，再来！',
    '刚才是跳了吗？我在回私信。',
  ],
  jump: [
    '好！这就是出片！',
    '发了，艾特你，你小红书叫啥？',
    '这条互动量要炸了。',
    '绝绝子！慢动作开着呢！',
    '好，这张就是封面了。',
    '这是大女主氛围感。',
    '算法要爱死这条了。',
    '刚才太完美了，谁都别动！',
  ],
  nearMiss: [
    '好险啊，但我好爱。',
    '好混乱，好真实，好有质感。',
    '这段很原生，零滤镜。',
    '我真的尖叫了，原声保留。',
    '这完全可以拍一期故事会。',
    '刺激感是这一季的流行色。',
  ],
  crash: [
    '我的假睫毛！',
    '好，这段剪掉。',
    '不是这个氛围，不是这个氛围。',
    '我的补光灯！',
    '危机公关！谁都不许发！',
    '这可不在我的情绪板上。',
  ],
  drift: [
    '这个漂移？绝了。',
    '好有东京漂移那味儿。',
    '天呐这个甩尾，我吹爆。',
    '侧脸其实是我最上镜的角度。',
    '太有电影感了，无人机呢？',
    '漂移季，我们爱漂移季。',
  ],
  slow: [
    '这速度一点都不出片。',
    '能不能……更上热搜一点？',
    '这节奏，观众要划走了。',
    '快点，我的动态24小时就过期了。',
    '这车在缓冲中吗？',
    '粉丝都在划过我们了。',
  ],
  timeLow: [
    '我自己的发布会要迟到了！',
    '快点，我的抹茶要化了！',
    '网红们都到了，我还没到！',
    '宝，五分钟后就解禁发稿了！',
    '我迟到就是品牌迟到，冲！',
    '我的黄金时段光线要没了！',
  ],
  dropoff: [
    '谢谢~我会艾特你的！',
    '五星好评，素材太顶了。',
    '爱了，下次一起联名。',
    '好，你正式成为品牌大使了。',
    '拜拜！看我动态，你上镜了！',
    '这一趟太有记忆点了，爱了。',
  ],
  walkout: [
    '烦死了，换一个机器人。',
    '这和我的品牌调性不符，拜。',
    '好的，这辆车我取关了。',
  ],
  idle: [
    '我们的品牌人设就是“松弛感”。',
    '我今天早上给我家狗换了个品牌定位。',
    '我们是生活方式品牌，卖ToB软件的。',
    '我的抹茶粉丝比我们CEO还多。',
    '我跟法务说“好的”，然后照样发了。',
    '我们的北极星指标是氛围感。',
    '我在出一款香薰，味道叫“第四季度”。',
  ],
  smash: [
    '等下再撞一次，我要个撞击特写。',
    '破坏感现在超火的。',
    '这很有品牌焕新的感觉，旧的不去。',
    '好疯，粉丝肯定爱看。',
  ],
  'good.air': [
    '滞空时间真的绝绝子。',
    '好，空镜素材已经够剪三条了。',
    '互动量在涨，宝继续飞。',
    '这条要成年度最出圈的视频了。',
  ],
  'bad.air': [
    '宝，贴地镜头不叫内容。',
    '这跟素材库的空镜一样，跳一个啊！',
    '不飞就没片，没片就没流量。',
    '我粉丝要看飞的，字面意思。',
  ],
  'good.drift': [
    '这个漂移太会了，继续。',
    '这慢动作也太出片了吧。',
    '侧滑素材质感拉满。',
    '我们要上热搜了，我能感觉到。',
  ],
  'bad.drift': [
    '宝，走直线已经过时了。',
    '漂移呢？慢动作在这儿干等着。',
    '这不是东京漂移，这是早高峰通勤。',
    '我答应品牌方有漂移的！漂起来！',
  ],
  carpool: [
    '来新人了！签个肖像授权哦，开玩笑的。不是。',
    '嗨，你在背景里待着就好，自然点。',
    '拼车vlog？好接地气，我可以。',
    '你好新朋友，你有多少粉丝？',
  ],
  premium: [
    '1.3倍？网红价嘛，可以。',
    '高端款？跟我的审美挺配。',
    '这些传感器好有杂志感，未来风。',
    '它道歉好温柔，品牌话术满分。',
  ],
  ram: [
    '我们刚把一辆车铲飞了？绝了。',
    '这才叫硬核官宣。',
    '让开宝，你挡我镜头了！',
  ],
};

// What they say when they tell you what they want (wants.ts).
export const asks = {
  en: {
    air: "Get some air. I'm filming.",
    drift: 'Drift it. Slow-mo is on.',
  },
  zh: {
    air: '飞一个，我在录呢。',
    drift: '漂一个，慢动作开好了。',
  },
} satisfies Asks;
