import type { Asks, Lines } from '../quips';

export const en: Lines = {
  pickup: [
    "Bro. Let's GO. I've got a pitch in ten.",
    'Yo, is this the robot one? Sick. Very on thesis.',
    "Quick ride, bro, I'm between two coffee chats.",
    "Bro, I'm closing a seed round on this ride. Vibes only.",
    'Sup. Hold my cold brew, wait, you have no hands.',
    "Let's go, bro. I already did a cold plunge today.",
    'Yo. Treat me like a Series A. Fast and irrational.',
    "Bro, my calendar is a hockey stick. Let's move.",
  ],
  jump: [
    "LET'S GOOO, this is going on my Strava.",
    'Bro we are LITERALLY flying. 10x.',
    "That's a hockey stick, bro.",
    'Up and to the right, bro! UP AND TO THE RIGHT!',
    'Zero gravity. Zero gross margin. Zero worries.',
    "Bro that's a moonshot. Literally a moonshot.",
    'Airborne! My VO2 max just went up.',
    'Send it, bro! SEND IT!',
  ],
  nearMiss: [
    'Bro! Move fast and miss things!',
    'Disruption, baby!',
    'Bro, that was a near-death growth hack.',
    "Missed 'em! That's product-market dodge, bro.",
    'Ooh, edge case! Love an edge case.',
    'My heart rate zone just went to five, bro.',
  ],
  crash: [
    'Bro, my cold brew!',
    "That's fine, that's a learning.",
    "We'll call that a pivot.",
    'Fail fast, bro. Love that.',
    "That's a feature, not a bug, bro.",
    'Bro, my fleece vest absorbed most of it. Tactical fleece.',
    "Okay, we'll fix it in the next sprint.",
  ],
  drift: [
    'Sideways like my cap table, bro.',
    'Drift mode. Love the UX.',
    "Bro, we're pivoting in real time.",
    'Lateral growth, bro. Lateral.',
    'Drifting like my runway, bro.',
    'This is my whole career path, bro. Sideways.',
  ],
  slow: [
    'Bro this ride has no product-market fit.',
    'Are we waiting on legal or what?',
    'Bro, my Strava thinks I died.',
    'This pace is very Series D, bro.',
    'Bro, I could run faster. I literally do ultras.',
    'Is this the enterprise tier? Feels enterprise.',
  ],
  timeLow: [
    "Bro I'm gonna miss the pitch!",
    'Bro. BRO. Hurry.',
    'The VCs leave at the top of the hour, bro!',
    "Bro, my deck has a 'traction' slide. GET TRACTION.",
    "Ship it, bro! We're out of runway!",
    "If I miss this I'm going back to consulting, bro.",
  ],
  dropoff: [
    "You're cracked, bro. Let's grab coffee sometime. We won't.",
    "Huge. I'll put you in the deck.",
    "Bro, you're a 10x driver. Want equity? It's worthless.",
    "Crushed it. I'll intro you to my guy. No I won't.",
    'Bro, logging that ride as a workout.',
    "Respect, bro. You're my new cofounder. Spiritually.",
  ],
  walkout: [
    "I'm just gonna scooter it, bro.",
    "Bro, I'll run there. It's a tempo day anyway.",
    "Churned, bro. You've churned me.",
  ],
  idle: [
    "So I'm building an AI for dogs. But B2B.",
    'I do cold plunges, so this ride is nothing.',
    'My sleep ring says my stress is top one percent.',
    "We're pre-revenue but post-vibes.",
    "It's like Uber, but for other Ubers.",
    'I only drink cold brew that was brewed colder, bro.',
    'I fast till 2pm. My brain is pure ketones rn.',
    "We're a team of 4 and 3 are AI agents. The fourth is me.",
  ],
  smash: [
    'Bro! We just disrupted that bench!',
    'Move fast and break things, literally, bro!',
    "That was legacy infrastructure, bro. It's fine.",
    'Creative destruction, baby!',
  ],
  'good.speed': [
    "THIS is velocity, bro. Investors love velocity.",
    'Bro we are blitzscaling right now.',
    'Fast, bro! Faster than my burn rate!',
    'This is the speed I want my startup to fail at.',
  ],
  'bad.speed': [
    'Bro, this is not blitzscaling. This is blitzcrawling.',
    'Bro, is the throttle gated behind a paywall?',
    'Move fast, bro. Has nobody told you? Move fast.',
    "My grandma's Peloton goes faster, bro.",
  ],
  'good.air': [
    'Bro, the vlog is gonna slap.',
    'This is so much hang time. Like my seed round.',
    'More air! My audience needs it, bro!',
    'Bro, this ride is a unicorn. It flies.',
  ],
  'bad.air': [
    'Bro, the vlog is all ground footage. Dead content.',
    'Bro, wheels down the whole time? Boring.',
    "Bro, this is a flat ride. Flat like my revenue.",
    "No jumps, bro? That's a pass from me.",
  ],
  'good.closecalls': [
    'Bro, threading needles like a term sheet!',
    "That's risk tolerance, bro. VCs dig it.",
    "Bro, you're an adrenaline-as-a-service platform.",
    "Close calls, bro! My HRV is thriving!",
  ],
  'bad.closecalls': [
    "Bro, you're driving like a compliance officer.",
    'Get closer to stuff, bro! Where is the risk?',
    "Bro, this ride has no edge. Literally no edges.",
    'Too safe, bro. Safe is how you die in a seed round.',
  ],
  carpool: [
    'Oh sick, a stranger. Bro, are you raising?',
    'Bro, welcome. Quick question: what do you do?',
    "Carpool? Bro, that's just networking with seatbelts.",
    'New rider! Bro, can I pitch you real quick?',
  ],
  premium: [
    "1.3x? Bro, that's a rounding error. Expense it.",
    "Premium, bro. I'll put it on the company card.",
    'Bro, this car has more sensors than my sleep ring.',
    "Bro, it apologized to me. Very enterprise.",
  ],
  ram: [
    'Bro, we just acquired that car. Hostile takeover.',
    'Out of the way, legacy player!',
    "Bro, that's how you take market share!",
  ],
};

export const zh: Lines = {
  pickup: [
    '兄弟，冲！我十分钟后要路演。',
    '哟，无人车？这赛道我看好。',
    '快点兄弟，我两个咖啡局之间挤出来的。',
    '兄弟，这一路我要把天使轮聊下来。',
    '走起，我今天已经冷水浴打过卡了。',
    '兄弟，按A轮的节奏开，快、狠、不讲理。',
    '我日程排满了，曲线比融资还陡，走！',
    '兄弟，先对齐一下：目标就是快。',
  ],
  jump: [
    '起飞啦！这必须发朋友圈打卡！',
    '兄弟我们真的在飞！十倍增长！',
    '这就是曲棍球杆曲线啊兄弟！',
    '起飞！这才叫风口上的猪！',
    '失重了！我的估值也跟着飘了！',
    '兄弟，这是登月级别的项目！',
    '腾空了！我心率区间直接拉满！',
    '冲冲冲！给我飞！',
  ],
  nearMiss: [
    '兄弟！快速迭代，擦身而过！',
    '颠覆！这就叫颠覆！',
    '兄弟，这波是极限增长黑客。',
    '躲开了！这叫风险对冲兄弟！',
    '哇，边界场景！我最爱边界场景！',
    '兄弟，我手表说我要心梗了。',
  ],
  crash: [
    '兄弟，我的冷萃！',
    '没事，这是一次复盘的机会。',
    '就当我们战略转型了。',
    '快速试错嘛兄弟，没毛病。',
    '兄弟，这不是bug，是feature。',
    '还好我穿了马甲，抗撞。',
    '行，下个迭代再修。',
  ],
  drift: [
    '兄弟，侧着走，跟我的股权结构一样。',
    '漂移模式，交互体验拉满。',
    '兄弟，我们在实时转型。',
    '横向拓展！这叫横向拓展！',
    '漂得跟我的现金流一样，兄弟。',
    '这就是我的职业路线，一路横着走。',
  ],
  slow: [
    '兄弟，这车没有产品市场契合度。',
    '等啥呢？等法务审批吗？',
    '兄弟，我手表以为我坐着睡着了。',
    '这速度，很有国企味儿啊兄弟。',
    '兄弟，我跑马拉松都比这快。',
    '这车是走流程的吧？颗粒度太粗了。',
  ],
  timeLow: [
    '兄弟，路演要迟到了！',
    '兄弟。兄弟！快点！',
    '投资人整点就走了兄弟！',
    '兄弟快点！我们的跑道要烧完了！',
    '赶不上我就回去当咨询狗了！',
    '兄弟，给点抓手啊，冲！',
  ],
  dropoff: [
    '兄弟你太猛了，改天约咖啡。约不了的。',
    '牛！我把你写进BP里。',
    '兄弟你是十倍司机，给你期权要不？不值钱的。',
    '漂亮，回头给你引荐我哥们。不会的。',
    '兄弟，这趟我记成一次有氧训练了。',
    'respect兄弟，精神上你是我合伙人。',
  ],
  walkout: [
    '算了兄弟，我扫个共享单车。',
    '兄弟，我跑过去，正好今天练节奏跑。',
    '兄弟，你把我流失掉了。',
  ],
  idle: [
    '我在做狗狗的AI。不过是ToB的。',
    '我天天冷水浴，这点颠簸算啥。',
    '我睡眠戒指说我压力全国前百分之一。',
    '我们还没营收，但氛围已经闭环了。',
    '这就是滴滴，但是给滴滴用的滴滴。',
    '我只喝更冷的冷萃，兄弟。',
    '我轻断食到下午两点，现在全靠酮体。',
    '我们团队四个人，三个是AI智能体，一个是我。',
  ],
  smash: [
    '兄弟！我们刚颠覆了一张长椅！',
    '快速行动，打破东西，字面意思！',
    '那是旧基建，兄弟，淘汰了。',
    '破坏式创新！爽！',
  ],
  'good.speed': [
    '这就是速度！投资人就爱看速度！',
    '兄弟，我们正在闪电式扩张！',
    '快！比我烧钱还快！',
    '这速度，赛道第一兄弟！',
  ],
  'bad.speed': [
    '兄弟，这不叫闪电扩张，这叫蜗牛扩张。',
    '兄弟，油门是会员功能吗？',
    '快点兄弟，没人跟你对齐过吗？要快！',
    '我奶奶的动感单车都比这快。',
  ],
  'good.air': [
    '兄弟，这vlog要爆了。',
    '滞空时间好长，跟我融资周期一样。',
    '再飞！粉丝要看这个兄弟！',
    '兄弟，这车是独角兽，会飞的那种。',
  ],
  'bad.air': [
    '兄弟，vlog全是地面镜头，没流量的。',
    '兄弟，一直贴地跑？太无聊了。',
    '这车跟我营收曲线一样平。',
    '不飞是吧？这个项目我pass了。',
  ],
  'good.closecalls': [
    '兄弟，穿针引线，跟抢投资条款一样！',
    '这就是风险偏好，投资人就吃这套！',
    '兄弟，你是肾上腺素即服务平台。',
    '擦边擦得好！我心率变异性拉满了！',
  ],
  'bad.closecalls': [
    '兄弟，你开得跟合规部的一样。',
    '靠近点兄弟！风险在哪？',
    '兄弟，这一路一点锋芒都没有。',
    '太稳了兄弟，稳就是死路一条。',
  ],
  carpool: [
    '哟，来了个陌生人。兄弟在融资吗？',
    '欢迎兄弟，问一下，你做哪个赛道的？',
    '拼车？兄弟，这就是系着安全带的社交局。',
    '新乘客！兄弟，给你讲讲我的项目？',
  ],
  premium: [
    '1.3倍？兄弟，误差而已，公司报销。',
    '高端局，兄弟，刷公司卡。',
    '兄弟，这车传感器比我睡眠戒指还多。',
    '它刚跟我道歉了，兄弟，很大厂。',
  ],
  ram: [
    '兄弟，那辆车被我们收购了，恶意收购。',
    '让开，传统玩家！',
    '兄弟，这就叫抢占市场份额！',
  ],
};

// What they say when they tell you what they want (wants.ts).
export const asks = {
  en: {
    speed: 'Move fast. Literally.',
    air: 'Do a sick jump. For the vlog.',
    closecalls: 'Thread the needle, bro.',
  },
  zh: {
    speed: '要快，兄弟。字面意义上的快。',
    air: '来个大跳，我要拍vlog。',
    closecalls: '兄弟，给我擦边走，刺激点。',
  },
} satisfies Asks;
